#include "../include/transpiler.h"
#include <stdexcept>
#include <cstdio>
#include <sstream>
#include <iostream>

Transpiler::Transpiler(const Program& program,
                       const std::string& filename,
                       const std::vector<std::string>& c_includes,
                       const std::vector<std::string>& cxx_includes,
                       ErrorReporter& reporter)
    : program(program), filename(filename),
      c_includes(c_includes), cxx_includes(cxx_includes),
      reporter(reporter), indent_level(0) {}

// ─── Helpers ────────────────────────────────────────────

void Transpiler::write(const std::string& s) { out << s; }

void Transpiler::writeln(const std::string& s) {
    out << indentStr() << s << "\n";
}

void Transpiler::indent() { indent_level++; }
void Transpiler::dedent() { if (indent_level > 0) indent_level--; }

std::string Transpiler::indentStr() {
    return std::string(indent_level * 4, ' ');
}

std::string Transpiler::badaTypeToCpp(const std::string& type) {
    if (type == "int")    return "int";
    if (type == "float")  return "float";
    if (type == "bool")   return "bool";
    if (type == "str")    return "const char*";
    if (type == "String") return "std::string";
    if (type == "any")    return "void*";
    if (type == "void")   return "void";
    if (type == "auto")   return "auto";
    if (type.size() > 2 &&
        type.front() == '[' && type.back() == ']') {
        std::string elem = type.substr(1, type.size() - 2);
        return "std::vector<" + badaTypeToCpp(elem) + ">";
    }
    return type;
}

std::string Transpiler::tempFileName(const std::string& output) {
    std::string base = output;
    size_t slash = base.rfind('/');
    if (slash != std::string::npos)
        base = base.substr(slash + 1);
    return "_bada_tmp_" + base + ".cpp";
}

// ─── Top Level ──────────────────────────────────────────

std::string Transpiler::generate() {
    out.str(""); out.clear();

    writeln("// Generated by Bada-Lang Compiler v1.2");
    writeln("// Source: " + filename);
    writeln("");

    genIncludes();

    bool has_stdlib = false;
    for (const auto& u : program.uses) {
        if (u.module == "bada") { has_stdlib = true; break; }
    }
    if (has_stdlib) {
        writeln("");
        writeln("// ─── Bada Standard Library ──────────────────────");
        genStdlibIncludes();
    }

    writeln("");
    writeln("#include <cstdio>");
    writeln("#include <cstring>");
    writeln("#include <vector>");
    writeln("#include <tuple>");
    writeln("#include <functional>");
    writeln("");

    if (!program.constants.empty()) {
        writeln("// ─── Constants ──────────────────────────────────");
        for (const auto& c : program.constants)
            genConstDecl(c);
        writeln("");
    }

    if (!program.extern_fns.empty()) {
        writeln("// ─── Extern Functions ───────────────────────────");
        for (const auto& e : program.extern_fns)
            genExternFn(e);
        writeln("");
    }

    for (const auto& s : program.structs) {
        genStructDecl(s);
        writeln("");
    }

    for (const auto& e : program.enums) {
        genEnumDecl(e);
        writeln("");
    }

    writeln("// ─── Forward Declarations ───────────────────────");
    for (const auto& fn : program.functions) {
        if (fn.name == "main") continue;
        std::string ret;
        if (!fn.return_types.empty()) {
            ret = "std::tuple<";
            for (size_t i = 0; i < fn.return_types.size(); i++) {
                if (i > 0) ret += ", ";
                ret += badaTypeToCpp(fn.return_types[i]);
            }
            ret += ">";
        } else {
            ret = badaTypeToCpp(
                fn.return_type.empty() ? "void" : fn.return_type);
        }
        std::string params;
        for (size_t i = 0; i < fn.params.size(); i++) {
            if (i > 0) params += ", ";
            params += badaTypeToCpp(fn.params[i].type) +
                      " " + fn.params[i].name;
        }
        writeln(ret + " " + fn.name + "(" + params + ");");
    }
    writeln("");

    writeln("// ─── Functions ──────────────────────────────────");
    for (const auto& fn : program.functions) {
        genFnDecl(fn);
        writeln("");
    }

    return out.str();
}

void Transpiler::genIncludes() {
    for (const auto& inc : c_includes)
        writeln("#include <" + inc + ">");
    for (const auto& inc : cxx_includes)
        writeln("#include <" + inc + ">");
}

void Transpiler::genStdlibIncludes() {
    for (const auto& u : program.uses) {
        if (u.module != "bada") continue;
        if (u.submodule == "io") {
            writeln("#include <iostream>");
            writeln("#include <string>");
        } else if (u.submodule == "math") {
            writeln("#include <cmath>");
            writeln("#include <algorithm>");
        } else if (u.submodule == "string") {
            writeln("#include <string>");
            writeln("#include <algorithm>");
            writeln("#include <sstream>");
        } else if (u.submodule == "array") {
            writeln("#include <vector>");
            writeln("#include <algorithm>");
        } else if (u.submodule == "mem") {
            writeln("#include <cstdlib>");
            writeln("#include <cstring>");
        }
    }
}

void Transpiler::genConstDecl(const ConstDecl& c) {
    writeln("const " + badaTypeToCpp(c.type) +
            " " + c.name + " = " + genExpr(*c.value) + ";");
}

void Transpiler::genExternFn(const ExternFnDecl& e) {
    std::string ret = badaTypeToCpp(
        e.return_type.empty() ? "void" : e.return_type);
    std::string params;
    for (size_t i = 0; i < e.params.size(); i++) {
        if (i > 0) params += ", ";
        params += badaTypeToCpp(e.params[i].type) +
                  " " + e.params[i].name;
    }
    writeln("extern \"C\" " + ret + " " + e.name +
            "(" + params + ");");
}

void Transpiler::genStructDecl(const StructDecl& s) {
    writeln("struct " + s.name + " {");
    indent();
    for (const auto& f : s.fields)
        writeln(badaTypeToCpp(f.type) + " " + f.name + ";");

    for (const auto& m : s.methods) {
        writeln("");
        std::string ret = badaTypeToCpp(
            m.return_type.empty() ? "void" : m.return_type);
        std::string params;
        for (size_t i = 0; i < m.params.size(); i++) {
            if (i > 0) params += ", ";
            params += badaTypeToCpp(m.params[i].type) +
                      " " + m.params[i].name;
        }
        writeln(ret + " " + m.name + "(" + params + ") {");
        indent();
        for (size_t j = 0; j < m.body.size(); j++) {
            const auto& stmt = m.body[j];
            if (j == m.body.size() - 1 &&
                !m.return_type.empty() &&
                m.return_type != "void") {
                if (auto* es = dynamic_cast<const ExprStmt*>(stmt.get())) {
                    writeln("return " + genExpr(*es->expr) + ";");
                    continue;
                }
            }
            genStmt(*stmt);
        }
        dedent();
        writeln("}");
    }
    dedent();
    writeln("};");
}

void Transpiler::genEnumDecl(const EnumDecl& e) {
    writeln("enum class " + e.name + " {");
    indent();
    for (size_t i = 0; i < e.variants.size(); i++) {
        std::string comma = (i < e.variants.size() - 1) ? "," : "";
        writeln(e.variants[i] + comma);
    }
    dedent();
    writeln("};");
}

void Transpiler::genFnDecl(const FnDecl& fn) {
    std::string ret;
    if (!fn.return_types.empty()) {
        ret = "std::tuple<";
        for (size_t i = 0; i < fn.return_types.size(); i++) {
            if (i > 0) ret += ", ";
            ret += badaTypeToCpp(fn.return_types[i]);
        }
        ret += ">";
    } else {
        ret = badaTypeToCpp(
            fn.return_type.empty() ? "void" : fn.return_type);
    }
    if (fn.name == "main") ret = "int";

    std::string params;
    for (size_t i = 0; i < fn.params.size(); i++) {
        if (i > 0) params += ", ";
        params += badaTypeToCpp(fn.params[i].type) +
                  " " + fn.params[i].name;
    }

    writeln(ret + " " + fn.name + "(" + params + ") {");
    indent();

    for (size_t j = 0; j < fn.body.size(); j++) {
        const auto& stmt = fn.body[j];
        if (j == fn.body.size() - 1 &&
            fn.return_type != "void" &&
            !fn.return_type.empty() &&
            fn.return_types.empty()) {
            if (auto* es = dynamic_cast<const ExprStmt*>(stmt.get())) {
                writeln("return " + genExpr(*es->expr) + ";");
                continue;
            }
        }
        genStmt(*stmt);
    }

    if (fn.name == "main") writeln("return 0;");
    dedent();
    writeln("}");
}

// ─── Statements ─────────────────────────────────────────

void Transpiler::genStmt(const Stmt& stmt) {
    if (auto* s = dynamic_cast<const VarDeclStmt*>(&stmt)) {
        genVarDecl(*s); return;
    }
    if (auto* s = dynamic_cast<const AssignStmt*>(&stmt)) {
        genAssign(*s); return;
    }
    if (auto* s = dynamic_cast<const ArrayAssignStmt*>(&stmt)) {
        genArrayAssign(*s); return;
    }
    if (auto* s = dynamic_cast<const FieldAssignStmt*>(&stmt)) {
        genFieldAssign(*s); return;
    }
    if (auto* s = dynamic_cast<const IfStmt*>(&stmt)) {
        genIf(*s); return;
    }
    if (auto* s = dynamic_cast<const WhileStmt*>(&stmt)) {
        genWhile(*s); return;
    }
    if (auto* s = dynamic_cast<const ForStmt*>(&stmt)) {
        genFor(*s); return;
    }
    if (auto* s = dynamic_cast<const ReturnStmt*>(&stmt)) {
        genReturn(*s); return;
    }
    if (auto* s = dynamic_cast<const MultiReturnStmt*>(&stmt)) {
        genMultiReturn(*s); return;
    }
    if (auto* s = dynamic_cast<const TupleDestructStmt*>(&stmt)) {
        genTupleDestruct(*s); return;
    }
    if (auto* s = dynamic_cast<const MatchStmt*>(&stmt)) {
        genMatch(*s); return;
    }
    if (auto* s = dynamic_cast<const AsmStmt*>(&stmt)) {
        genAsm(*s); return;
    }
    if (auto* s = dynamic_cast<const CxxStmt*>(&stmt)) {
        out << s->code << "\n"; return;
    }
    if (dynamic_cast<const BreakStmt*>(&stmt)) {
        writeln("break;"); return;
    }
    if (dynamic_cast<const ContinueStmt*>(&stmt)) {
        writeln("continue;"); return;
    }
    if (auto* s = dynamic_cast<const ExprStmt*>(&stmt)) {
        genExprStmt(*s); return;
    }
}

void Transpiler::genVarDecl(const VarDeclStmt& stmt) {
    if (!stmt.init) return;
    std::string type = badaTypeToCpp(stmt.type);
    std::string val  = genExpr(*stmt.init);
    if (stmt.type == "auto")
        writeln("auto " + stmt.name + " = " + val + ";");
    else
        writeln(type + " " + stmt.name + " = " + val + ";");
}

void Transpiler::genAssign(const AssignStmt& stmt) {
    writeln(stmt.name + " = " + genExpr(*stmt.value) + ";");
}

void Transpiler::genArrayAssign(const ArrayAssignStmt& stmt) {
    writeln(stmt.name + "[" + genExpr(*stmt.index) + "] = " +
            genExpr(*stmt.value) + ";");
}

void Transpiler::genFieldAssign(const FieldAssignStmt& stmt) {
    writeln(stmt.object + "." + stmt.field +
            " = " + genExpr(*stmt.value) + ";");
}

void Transpiler::genIf(const IfStmt& stmt) {
    writeln("if (" + genExpr(*stmt.condition) + ") {");
    indent();
    for (const auto& s : stmt.then_body) genStmt(*s);
    dedent();
    if (!stmt.else_body.empty()) {
        writeln("} else {");
        indent();
        for (const auto& s : stmt.else_body) genStmt(*s);
        dedent();
    }
    writeln("}");
}

void Transpiler::genWhile(const WhileStmt& stmt) {
    writeln("while (" + genExpr(*stmt.condition) + ") {");
    indent();
    for (const auto& s : stmt.body) genStmt(*s);
    dedent();
    writeln("}");
}

void Transpiler::genFor(const ForStmt& stmt) {
    std::string start = genExpr(*stmt.start);
    std::string end   = genExpr(*stmt.end);
    std::string cmp   = stmt.inclusive ? "<=" : "<";
    writeln("for (int " + stmt.var + " = " + start +
            "; " + stmt.var + " " + cmp + " " + end +
            "; " + stmt.var + "++) {");
    indent();
    for (const auto& s : stmt.body) genStmt(*s);
    dedent();
    writeln("}");
}

void Transpiler::genReturn(const ReturnStmt& stmt) {
    writeln("return " + genExpr(*stmt.value) + ";");
}

void Transpiler::genMultiReturn(const MultiReturnStmt& stmt) {
    std::string vals;
    for (size_t i = 0; i < stmt.values.size(); i++) {
        if (i > 0) vals += ", ";
        vals += genExpr(*stmt.values[i]);
    }
    writeln("return std::make_tuple(" + vals + ");");
}

void Transpiler::genTupleDestruct(const TupleDestructStmt& stmt) {
    std::string names;
    for (size_t i = 0; i < stmt.names.size(); i++) {
        if (i > 0) names += ", ";
        names += stmt.names[i];
    }
    writeln("auto [" + names + "] = " +
            genExpr(*stmt.value) + ";");
}

void Transpiler::genMatch(const MatchStmt& stmt) {
    std::string val = genExpr(*stmt.value);
    bool first = true;
    for (const auto& arm : stmt.arms) {
        std::string cmp = arm.enum_name + "::" + arm.variant;
        if (first) {
            writeln("if (" + val + " == " + cmp + ") {");
            first = false;
        } else {
            writeln("} else if (" + val + " == " + cmp + ") {");
        }
        indent();
        for (const auto& s : arm.body) genStmt(*s);
        dedent();
    }
    if (!stmt.arms.empty()) writeln("}");
}

void Transpiler::genAsm(const AsmStmt& stmt) {
    std::string code;
    for (char c : stmt.code) {
        if (c == '\n' || c == '\r') code += ' ';
        else if (c == '"') code += "\\\"";
        else code += c;
    }
    size_t start = code.find_first_not_of(' ');
    size_t end   = code.find_last_not_of(' ');
    if (start != std::string::npos)
        code = code.substr(start, end - start + 1);
    writeln("__asm__ volatile(\"" + code + "\");");
}

void Transpiler::genExprStmt(const ExprStmt& stmt) {
    writeln(genExpr(*stmt.expr) + ";");
}

// ─── Expressions ────────────────────────────────────────

std::string Transpiler::genExpr(const Expr& expr) {
    if (auto* e = dynamic_cast<const IntLitExpr*>(&expr))
        return genIntLit(*e);
    if (auto* e = dynamic_cast<const FloatLitExpr*>(&expr))
        return genFloatLit(*e);
    if (auto* e = dynamic_cast<const StrLitExpr*>(&expr))
        return genStrLit(*e);
    if (auto* e = dynamic_cast<const BoolLitExpr*>(&expr))
        return genBoolLit(*e);
    if (auto* e = dynamic_cast<const IdentExpr*>(&expr))
        return genIdent(*e);
    if (auto* e = dynamic_cast<const BinOpExpr*>(&expr))
        return genBinOp(*e);
    if (auto* e = dynamic_cast<const CallExpr*>(&expr))
        return genCall(*e);
    if (auto* e = dynamic_cast<const PrintfExpr*>(&expr))
        return genPrintf(*e);
    if (auto* e = dynamic_cast<const StructLitExpr*>(&expr))
        return genStructLit(*e);
    if (auto* e = dynamic_cast<const FieldAccessExpr*>(&expr))
        return genFieldAccess(*e);
    if (auto* e = dynamic_cast<const EnumVariantExpr*>(&expr))
        return genEnumVariant(*e);
    if (auto* e = dynamic_cast<const ArrayLitExpr*>(&expr))
        return genArrayLit(*e);
    if (auto* e = dynamic_cast<const ArrayIndexExpr*>(&expr))
        return genArrayIndex(*e);
    if (auto* e = dynamic_cast<const CastExpr*>(&expr))
        return genCast(*e);
    if (auto* e = dynamic_cast<const RefExpr*>(&expr))
        return genRef(*e);
    if (auto* e = dynamic_cast<const MethodCallExpr*>(&expr))
        return genMethodCall(*e);
    if (auto* e = dynamic_cast<const ClosureExpr*>(&expr))
        return genClosure(*e);
    if (auto* e = dynamic_cast<const TupleExpr*>(&expr))
        return genTuple(*e);
    if (auto* e = dynamic_cast<const ResultExpr*>(&expr))
        return genResult(*e);
    if (auto* e = dynamic_cast<const ErrorPropExpr*>(&expr))
        return genErrorProp(*e);
    if (auto* e = dynamic_cast<const AnyExpr*>(&expr))
        return genExpr(*e->value);
    return "/* unknown */";
}

std::string Transpiler::genIntLit(const IntLitExpr& expr) {
    return std::to_string(expr.value);
}

std::string Transpiler::genFloatLit(const FloatLitExpr& expr) {
    return std::to_string(expr.value) + "f";
}

std::string Transpiler::genStrLit(const StrLitExpr& expr) {
    return "\"" + expr.value + "\"";
}

std::string Transpiler::genBoolLit(const BoolLitExpr& expr) {
    return expr.value ? "true" : "false";
}

std::string Transpiler::genIdent(const IdentExpr& expr) {
    return expr.name;
}

std::string Transpiler::genBinOp(const BinOpExpr& expr) {
    if (!expr.left)
        return expr.op + genExpr(*expr.right);
    return "(" + genExpr(*expr.left) +
           " " + expr.op + " " +
           genExpr(*expr.right) + ")";
}

std::string Transpiler::genCall(const CallExpr& expr) {
    std::string args;
    for (size_t i = 0; i < expr.args.size(); i++) {
        if (i > 0) args += ", ";
        args += genExpr(*expr.args[i]);
    }
    return expr.callee + "(" + args + ")";
}

std::string Transpiler::genPrintf(const PrintfExpr& expr) {
    std::string fmt = expr.format;
    if (expr.is_brace_style) {
        std::string result;
        size_t i = 0;
        while (i < fmt.size()) {
            if (fmt[i] == '{' && i+1 < fmt.size() && fmt[i+1] == '}') {
                result += "%d"; i += 2;
            } else { result += fmt[i++]; }
        }
        fmt = result;
    }
    if (fmt.empty() || fmt.back() != '\n') fmt += "\\n";
    std::string args;
    for (const auto& arg : expr.args)
        args += ", " + genExpr(*arg);
    return "printf(\"" + fmt + "\"" + args + ")";
}

std::string Transpiler::genStructLit(const StructLitExpr& expr) {
    std::string fields;
    for (size_t i = 0; i < expr.fields.size(); i++) {
        if (i > 0) fields += ", ";
        fields += "." + expr.fields[i].first +
                  " = " + genExpr(*expr.fields[i].second);
    }
    return expr.struct_name + "{" + fields + "}";
}

std::string Transpiler::genFieldAccess(const FieldAccessExpr& expr) {
    return genExpr(*expr.object) + "." + expr.field;
}

std::string Transpiler::genEnumVariant(const EnumVariantExpr& expr) {
    return expr.enum_name + "::" + expr.variant;
}

std::string Transpiler::genArrayLit(const ArrayLitExpr& expr) {
    std::string elems;
    for (size_t i = 0; i < expr.elements.size(); i++) {
        if (i > 0) elems += ", ";
        elems += genExpr(*expr.elements[i]);
    }
    return "{" + elems + "}";
}

std::string Transpiler::genArrayIndex(const ArrayIndexExpr& expr) {
    return genExpr(*expr.array) + "[" + genExpr(*expr.index) + "]";
}

std::string Transpiler::genCast(const CastExpr& expr) {
    return "(" + badaTypeToCpp(expr.target_type) + ")" +
           genExpr(*expr.value);
}

std::string Transpiler::genRef(const RefExpr& expr) {
    return "&(" + genExpr(*expr.value) + ")";
}

std::string Transpiler::genMethodCall(const MethodCallExpr& expr) {
    std::string args;
    for (size_t i = 0; i < expr.args.size(); i++) {
        if (i > 0) args += ", ";
        args += genExpr(*expr.args[i]);
    }
    std::string obj = genExpr(*expr.object);

    if (expr.method == "len")   return obj + ".size()";
    if (expr.method == "push")  return obj + ".push_back(" + args + ")";
    if (expr.method == "pop")   return obj + ".pop_back()";
    if (expr.method == "sort")  return "std::sort(" + obj + ".begin(), " + obj + ".end())";
    if (expr.method == "upper") return "std::transform(" + obj + ".begin(), " + obj + ".end(), " + obj + ".begin(), ::toupper), " + obj;
    if (expr.method == "lower") return "std::transform(" + obj + ".begin(), " + obj + ".end(), " + obj + ".begin(), ::tolower), " + obj;

    return obj + "." + expr.method + "(" + args + ")";
}

std::string Transpiler::genClosure(const ClosureExpr& expr) {
    std::string params;
    for (size_t i = 0; i < expr.params.size(); i++) {
        if (i > 0) params += ", ";
        params += badaTypeToCpp(expr.params[i].first) +
                  " " + expr.params[i].second;
    }
    std::string ret = badaTypeToCpp(
        expr.return_type.empty() ? "void" : expr.return_type
    );

    // Generate body
    std::ostringstream body_out;
    int saved = indent_level;
    indent_level = 1;
    std::ostringstream saved_out;
    saved_out << out.str();

    // Temporarily redirect output
    out.str(""); out.clear();
    for (size_t j = 0; j < expr.body.size(); j++) {
        const auto& stmt = expr.body[j];
        if (j == expr.body.size() - 1 &&
            !expr.return_type.empty() &&
            expr.return_type != "void") {
            if (auto* es = dynamic_cast<const ExprStmt*>(stmt.get())) {
                writeln("return " + genExpr(*es->expr) + ";");
                continue;
            }
        }
        genStmt(*stmt);
    }
    std::string body_str = out.str();

    // Restore
    out.str(""); out.clear();
    out << saved_out.str();
    indent_level = saved;

    return "[&](" + params + ") -> " + ret + " {\n" +
           body_str + indentStr() + "}";
}

std::string Transpiler::genTuple(const TupleExpr& expr) {
    std::string elems;
    for (size_t i = 0; i < expr.elements.size(); i++) {
        if (i > 0) elems += ", ";
        elems += genExpr(*expr.elements[i]);
    }
    return "std::make_tuple(" + elems + ")";
}

std::string Transpiler::genResult(const ResultExpr& expr) {
    if (expr.is_ok)
        return genExpr(*expr.value);
    return "/* Err(" + genExpr(*expr.value) + ") */";
}

std::string Transpiler::genErrorProp(const ErrorPropExpr& expr) {
    return genExpr(*expr.value);
}

// ─── Compile ────────────────────────────────────────────

void Transpiler::compile(const std::string& output_path) {
    std::string cpp_code = generate();
    std::string tmp_file = tempFileName(output_path);

    FILE* f = fopen(tmp_file.c_str(), "w");
    if (!f)
        reporter.fatal(ErrorCode::E006_CANNOT_OPEN_FILE,
                       "cannot write temp file: " + tmp_file);
    fwrite(cpp_code.c_str(), 1, cpp_code.size(), f);
    fclose(f);

    std::string cmd = "clang++ -std=c++17 -O2 ";
    cmd += tmp_file + " -o " + output_path;

    for (const auto& inc : c_includes)
        if (inc.find("math") != std::string::npos) cmd += " -lm";

    for (const auto& u : program.uses)
        if (u.module == "bada" && u.submodule == "math")
            cmd += " -lm";

    int ret = system(cmd.c_str());
    std::remove(tmp_file.c_str());

    if (ret != 0)
        reporter.fatal(ErrorCode::E010_LLVM_VERIFY_FAILED,
                       "C++ compilation failed");
}
